apiVersion: batch/v1
kind: Job
metadata:
  name: pi-calculation
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.34
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]  # Вычисление числа π
      restartPolicy: Never  # Или OnFailure
  backoffLimit: 4  # Максимальное количество повторных попыток