apiVersion: v1
kind: Pod
metadata:
  name: test-gephem
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: data
          mountPath: "/data"
  volumes:
    - name: data
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
            storageClassName: "fast-storage"  # Использует StorageClass